name: swimsense
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h74842e3_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.1=hecca717_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.14.1=ha770c72_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=11.0.0=h76408a6_0
  - icu=75.1=he02047a_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_4
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h2d0b736_3
  - numpy=2.0.2=py39h9cb892a_1
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h1b6b32d_0
  - pcre2=10.44=hc749103_2
  - pillow=11.3.0=py39h15c0740_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.3=pyhe01879c_2
  - pyserial=3.5=pyhd8ed1ab_1
  - pyside6=6.9.0=py39h0383914_0
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py39hd399759_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - heartpy==1.2.7

prefix: "/home/smonzon/.local/share/mamba/envs/swimsense"
